### ISSUE TITLE
Change manifest to support mobile version

### ISSUE THREAD

**Issue by TimReset** [dzruyk/obsidian-asciidoc#3]
Hi!
Before I wanted to thank you for your the greatest job! Supporting asciidoc in obsidian - it's the biggest thing!
So, one small comment - current version is obviously supporting mobile app (because you use the standard asciidoc.js render and I tested it by changing that value manually). So, could you pls set "isDesktopOnly": false?

**Comment by dzruyk** [comment]
Hello. Thank you for your kind words.

Sadly, I don't use the mobile version of the app at all. Today I launched it on android for the first time. Surprisingly almost everything works, but there are problems with asciidoc links handling. I try to fix it on this weekend.

When i tap on any link in asciidoc's preview application hangs. Can you please approve you have the same issue?

**Comment by TimReset** [comment]
I've checked links:
External links (eg https://google.com) work fine.
But internal one (eg toc) creates new files (Untitled, Untitled 1, etc).
But no any hangs.
